@host=http://localhost:7139
GET {{host}}/init-networks/sigfoxID/lorawanID
###

POST {{host}}/sigfox/sigfoxID
Accept: application/json
Content-Type: application/json
{
    "lqi": "Average",
    "duplicates": [
        {"bsId": "27EF", "rssi": -134, "nbRep": 2},
        {"bsId": "2797", "rssi": -132, "nbRep": 2},
        {"bsId": "2789", "rssi": -147, "nbRep": 1}
    ]
}
###

POST {{host}}/lorawan/lorawanID
Accept: application/json
Content-Type: application/json
{
    "metadata": {
        "network": {
            "lora": {
                "signalLevel": 5,
                "gatewayCnt": 3
            }
        }
    }
}
###

GET {{host}}/sigfox/sigfoxID
###

GET {{host}}/lorawan/lorawanID
###
