@host=http://localhost:7139
GET {{host}}/init-networks/21/loraWanDeviceId
###

POST {{host}}/sigfox/309DB8D
Accept: application/json
###

POST {{host}}/lorawan/0080E11500423076
Accept: application/json
Accept: application/json
Content-Type: application/json

{
    "metadata": {
        "network": {
            "lora": {
                "signalLevel": 75,
                "gatewayCnt": 3
            }
        }
    }
}
###

GET {{host}}/sigfox/21
###

GET {{host}}/lorawan/0080E11500423076
###

